name: Java CI

on: [workflow_dispatch, push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repair-Upgrader
      uses: actions/checkout@v3
      with:
        path: Repair-Upgrader
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Cache Maven packages
      id: cacheMain
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2
        restore-keys: ${{ runner.os }}-m2

    # Build Repair-Upgrader
    - name: Build Repair-Upgrader
      run: mvn -B package -T 1C --file Repair-Upgrader/pom.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Stage jar
      run: mkdir staging && cp Repair-Upgrader/target/Repair-Upgrader.jar staging
    - name: Rename jar
      run: mv staging/Repair-Upgrader*.jar staging/Repair-Upgrader_$GITHUB_SHA.jar
    - name: Upload jar
      uses: actions/upload-artifact@v3
      with:
        name: Repair-Upgrader_Dev-Build
        path: staging/Repair-Upgrader_*.jar
